---
- name: Install Prometheus and Grafana on EKS
  hosts: localhost
  connection: local
  tasks:
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        name: monitoring
        kind: Namespace
        state: present

    - name: Add Prometheus community helm repo
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Update helm repositories
      kubernetes.core.helm:
        name: dummy
        namespace: monitoring
        update_repo_cache: yes

    - name: Install kube-prometheus-stack via Helm
      kubernetes.core.helm:
        name: kube-stack
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        state: present
        values:
          grafana:
            service:
              type: LoadBalancer  # 외부 접속을 위해 로드밸런서 설정